"""Auto-comment: search posts by keyword, post AI-generated comments.

THIS IS THE HIGHEST-RISK TIER 3 FEATURE. Comments are the #1 way LinkedIn
detects inauthentic behavior. Defaults are very tight:

    daily limit: 5 comments
    hourly limit: 1 comment
    cooldown: 60-300 seconds
    min post age: 1 hour (don't pile onto fresh posts)
    max post age: 7 days (don't revive dead threads)
    min author connections: 1 (don't comment on strangers — looks like spam)
    blacklist: 30+ spammy phrases ("check out my", "DM me", "link in bio", ...)

The AI comment is generated by an injected `draft_fn(text) -> str` so the
test suite can verify the pipeline without a real LLM call. In production,
this is wired to the local drafter module.

Flow:
    search_by_keyword("agentic AI") -> [Post, ...]
    For each post:
        if post.age not in [1h, 7d]: skip
        if author not in 1st-degree network: skip
        if any blacklist phrase in post.text: skip
        draft = draft_fn(post.text)  # AI generates comment
        if any blacklist phrase in draft: skip (refuse to post)
        decision = gate.check("comment", target=urn, target_text=post.text)
        if allowed and not dry_run:
            comment_fn(urn, draft)
"""

from __future__ import annotations

import logging
import re
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

from .auto_like import PostTarget
from .ban_safety import SafetyDecision, SafetyGate

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Defaults — the strictest tier 3 feature
# ---------------------------------------------------------------------------

DEFAULT_BLACKLIST_PHRASES = [
    "check out my",
    "check out our",
    "DM me",
    "link in bio",
    "link in comments",
    "join my newsletter",
    "buy now",
    "discount code",
    "limited time offer",
    "make money fast",
    "click here",
    "follow me",
    "follow for follow",
    "f4f",
    "sub4sub",
    "🔥🔥🔥",
    "💰💰💰",
    "💵💵💵",
    "guaranteed results",
    "risk-free",
    "act now",
    "100% free",
    "earn $",
    "$$$",
    "easy money",
    "passive income",
    "no experience needed",
    "work from home",
    "be your own boss",
    "mlm",
    "crypto airdrop",
    "presale",
    "pump",
    "rug pull",
    "whatsapp me",
    "telegram group",
    "onlyfans",
]

# Allowed characters / max length for safety
MAX_COMMENT_LENGTH = 700  # LinkedIn hard limit is 1000, leave headroom
MIN_COMMENT_LENGTH = 20   # don't post 1-word drive-bys


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


@dataclass
class CommentTarget:
    """A post eligible for commenting, with extra safety metadata."""

    post: PostTarget
    posted_at: str
    author_is_connection: bool = False
    is_revived_thread: bool = False  # True if older than 3 days

    def age_hours(self) -> float:
        try:
            t = datetime.fromisoformat(self.posted_at)
            if t.tzinfo is None:
                t = t.replace(tzinfo=UTC)
            return (datetime.now(UTC) - t).total_seconds() / 3600
        except (ValueError, TypeError):
            return 0.0


@dataclass
class CommentActionResult:
    urn: str
    author: str
    decision: SafetyDecision
    draft: str = ""
    skip_reason: str = ""
    executed: bool = False
    error: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "urn": self.urn,
            "author": self.author,
            "decision": self.decision.to_dict(),
            "draft": self.draft,
            "skip_reason": self.skip_reason,
            "executed": self.executed,
            "error": self.error,
        }


@dataclass
class CommentCampaignResult:
    keyword: str
    found: int = 0
    eligible: int = 0
    drafted: int = 0
    allowed: int = 0
    executed: int = 0
    denied: int = 0
    dry_run: int = 0
    skipped: int = 0
    errors: int = 0
    results: list[CommentActionResult] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "keyword": self.keyword,
            "found": self.found,
            "eligible": self.eligible,
            "drafted": self.drafted,
            "allowed": self.allowed,
            "executed": self.executed,
            "denied": self.denied,
            "dry_run": self.dry_run,
            "skipped": self.skipped,
            "errors": self.errors,
            "results": [r.to_dict() for r in self.results],
        }


# ---------------------------------------------------------------------------
# Comment safety filters (independent of SafetyGate — pre-screen)
# ---------------------------------------------------------------------------


class CommentFilter:
    """Pre-screen posts and drafts before they reach the safety gate."""

    def __init__(
        self,
        *,
        blacklist_phrases: list[str] | None = None,
        min_age_hours: float = 1.0,
        max_age_days: float = 7.0,
        min_post_length: int = 50,
        min_comment_length: int = MIN_COMMENT_LENGTH,
        max_comment_length: int = MAX_COMMENT_LENGTH,
    ) -> None:
        self.blacklist_phrases = [
            p.lower() for p in (blacklist_phrases if blacklist_phrases is not None else DEFAULT_BLACKLIST_PHRASES)
        ]
        self.min_age_hours = min_age_hours
        self.max_age_days = max_age_days
        self.min_post_length = min_post_length
        self.min_comment_length = min_comment_length
        self.max_comment_length = max_comment_length

    def is_eligible(self, target: CommentTarget) -> tuple[bool, str]:
        """Check if post is eligible for commenting."""
        age_h = target.age_hours()
        if age_h < self.min_age_hours:
            return False, f"too fresh ({age_h:.1f}h < {self.min_age_hours}h)"
        if age_h > self.max_age_days * 24:
            return False, f"too old ({age_h / 24:.1f}d > {self.max_age_days}d)"
        if len(target.post.text) < self.min_post_length:
            return False, f"post too short ({len(target.post.text)} chars)"
        if not target.author_is_connection:
            return False, "author not in 1st-degree network"
        if self._has_blacklist(target.post.text):
            return False, "post contains blacklist phrase"
        return True, "ok"

    def is_safe_draft(self, draft: str) -> tuple[bool, str]:
        """Check if AI-generated draft is safe to post."""
        if len(draft) < self.min_comment_length:
            return False, f"draft too short ({len(draft)} chars)"
        if len(draft) > self.max_comment_length:
            return False, f"draft too long ({len(draft)} chars)"
        if self._has_blacklist(draft):
            return False, "draft contains blacklist phrase"
        # No URLs allowed in auto-comments
        if re.search(r"https?://", draft):
            return False, "draft contains URL"
        # No @-mentions of strangers (only allow @ in self-mention pattern)
        if re.search(r"@[A-Za-z0-9_]{2,}", draft):
            return False, "draft contains @-mention"
        # Excessive punctuation / caps
        if sum(1 for c in draft if c.isupper()) / max(len(draft), 1) > 0.5:
            return False, "draft has too many caps"
        if draft.count("!") > 3:
            return False, "draft has too many exclamation marks"
        return True, "ok"

    def _has_blacklist(self, text: str) -> bool:
        text_lc = text.lower()
        return any(p in text_lc for p in self.blacklist_phrases)


# ---------------------------------------------------------------------------
# Auto-comment
# ---------------------------------------------------------------------------


SearchFn = Callable[[str, int], list[CommentTarget]]
DraftFn = Callable[[str], str]
CommentFn = Callable[[str, str], bool]


class AutoComment:
    """Run a keyword-based auto-comment campaign through safety filters + gate."""

    def __init__(self, gate: SafetyGate, filter_: CommentFilter | None = None) -> None:
        self.gate = gate
        self.filter = filter_ or CommentFilter()

    def run(
        self,
        keyword: str,
        *,
        search_fn: SearchFn,
        draft_fn: DraftFn,
        comment_fn: CommentFn,
        max_results: int = 5,
    ) -> CommentCampaignResult:
        """Search → filter → draft → gate → post."""
        result = CommentCampaignResult(keyword=keyword)
        targets = search_fn(keyword, max_results) or []
        result.found = len(targets)

        for target in targets:
            ar = CommentActionResult(
                urn=target.post.urn, author=target.post.author,
                decision=SafetyDecision(
                    allowed=False, reason="not evaluated",
                    action_type="comment", target=target.post.urn,
                ),
            )
            # Pre-screen eligibility
            eligible, reason = self.filter.is_eligible(target)
            if not eligible:
                ar.skip_reason = reason
                result.skipped += 1
                result.results.append(ar)
                continue
            result.eligible += 1

            # Generate draft
            try:
                draft = draft_fn(target.post.text)
            except Exception as exc:
                ar.skip_reason = f"draft error: {exc}"
                ar.error = str(exc)
                result.errors += 1
                result.results.append(ar)
                continue
            ar.draft = draft
            result.drafted += 1

            # Filter draft
            safe, reason = self.filter.is_safe_draft(draft)
            if not safe:
                ar.skip_reason = reason
                result.skipped += 1
                result.results.append(ar)
                continue

            # Safety gate
            decision = self.gate.check(
                "comment", target=target.post.urn, target_text=target.post.text
            )
            ar.decision = decision
            if not decision.allowed:
                if decision.dry_run:
                    result.dry_run += 1
                else:
                    result.denied += 1
                result.results.append(ar)
                continue
            result.allowed += 1

            # Post
            try:
                ok = comment_fn(target.post.urn, draft)
                if ok:
                    ar.executed = True
                    result.executed += 1
                else:
                    ar.error = "comment_fn returned False"
                    result.errors += 1
            except Exception as exc:
                ar.error = str(exc)
                result.errors += 1
                log.warning("Comment failed for %s: %s", target.post.urn, exc)
            result.results.append(ar)

        return result
